[04/Dec/2015 17:52:49] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[04/Dec/2015 17:52:49] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[04/Dec/2015 17:53:04] WARNING [django.request:170] Not Found: /favicon.ico
[04/Dec/2015 18:19:11] WARNING [django.request:170] Not Found: /
[04/Dec/2015 20:30:40] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[04/Dec/2015 20:30:40] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[04/Dec/2015 20:42:34] ERROR [django.request:256] Internal Server Error: /factors/analysis/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\sanju\Master's\DVA\Project\Main\factors\views.py", line 70, in analysis
    output = factorIncome.doAnalysis(json_obj["city"], json_obj["state"], "restaurants", json_obj)
KeyError: 'city'
[04/Dec/2015 20:43:27] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[04/Dec/2015 20:43:27] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[04/Dec/2015 21:15:52] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[04/Dec/2015 21:15:52] DEBUG [django.db.backends:89] (0.016) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[04/Dec/2015 21:20:13] ERROR [django.request:256] Internal Server Error: /rest/reststats/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\sanju\Master's\DVA\Project\Main\reststats\views.py", line 140, in getRestStats
    cn=cursor.execute(query)
sqlite3.OperationalError: near "orcategories": syntax error
[04/Dec/2015 22:25:56] ERROR [django.request:256] Internal Server Error: /factors/home/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\sanju\Master's\DVA\Project\Main\factors\views.py", line 53, in home
    del fields['General']['Review_Count']
KeyError: 'Review_Count'
[04/Dec/2015 22:26:18] DEBUG [django.db.backends:89] (0.016) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[04/Dec/2015 22:26:18] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[04/Dec/2015 22:26:57] ERROR [django.request:256] Internal Server Error: /factors/home/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\sanju\Master's\DVA\Project\Main\factors\views.py", line 53, in home
    del fields['General']['Review_Count']
KeyError: 'Review_Count'
[04/Dec/2015 22:27:11] ERROR [django.request:256] Internal Server Error: /factors/home/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\sanju\Master's\DVA\Project\Main\factors\views.py", line 53, in home
    del fields['General']['Review_Count']
KeyError: 'Review_Count'
[04/Dec/2015 22:27:15] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[04/Dec/2015 22:27:15] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
